// Shared universities data used by compare UI
window.universities = {
  kennesaw: {
    name: 'Kennesaw State University',
    location: 'Kennesaw & Marietta, Georgia, USA',
    enrollment: '~47,845',
    in: '$7,548',
    out: '$21,616',
    acceptance: 'N/A',
    acceptanceRate: null,
    avgSalary: '$58,000',
    notablePrograms: ['Software Engineering', 'Cybersecurity', 'Business'],
    strengths: 'Large campus, practical programs, close industry connections to Atlanta.',
    costOfLivingIndex: 85,
    pros: 'Close to Atlanta; diverse programs; growing research profile.',
    page: 'kennesaw.html'
  },
  gsu: {
    name: 'Georgia State University',
    location: 'Atlanta, Georgia, USA',
    enrollment: '~52,000',
    in: '$12,500',
    out: '$33,320',
    acceptance: 'Varies',
    acceptanceRate: null,
    avgSalary: '$61,000',
    notablePrograms: ['Data Science', 'Business Analytics', 'Computer Science'],
    strengths: 'Urban campus with strong industry partnerships and internship pipelines.',
    costOfLivingIndex: 88,
    pros: 'Diverse student body; urban setting; strong academic reputation.',
    page: 'gsu.html'
  },
  gatech: {
    name: 'Georgia Tech',
    location: 'Atlanta, Georgia, USA',
    enrollment: '~43,000',
    in: '$10,512',
    out: '$33,596',
    acceptance: '~12–15%',
    acceptanceRate: 0.13,
    avgSalary: '$125,000',
    notablePrograms: ['Computer Science', 'Electrical Engineering', 'Human-Computer Interaction'],
    strengths: 'Top-tier engineering and CS research; deep industry ties and strong career outcomes.',
    costOfLivingIndex: 88,
    pros: 'World-class STEM reputation; strong alumni network; Atlanta industry links.',
    page: 'gatech.html'
  },
  utaustin: {
    name: 'The University of Texas at Austin',
    location: 'Austin, Texas, USA',
    enrollment: '~51,000',
    in: '$11,000',
    out: '$40,000+',
    acceptance: 'Selective',
    acceptanceRate: 0.3,
    avgSalary: '$110,000',
    notablePrograms: ['Software Engineering', 'Systems', 'AI/ML'],
    strengths: 'Strong CS program with excellent ties to Austin tech employers and startups.',
    costOfLivingIndex: 95,
    pros: 'Top CS program in Texas; strong research and industry connections.',
    page: 'utaustin.html'
  },
  tamu: {
    name: 'Texas A&M University',
    location: 'College Station, Texas, USA',
    enrollment: '~70,000',
    in: '$12,000',
    out: '$40,000',
    acceptance: 'Selective',
    acceptanceRate: 0.45,
    avgSalary: '$92,000',
    notablePrograms: ['Engineering', 'Computer Science', 'Agricultural Engineering'],
    strengths: 'Large research university with strong engineering pipelines and practical programs.',
    costOfLivingIndex: 75,
    pros: 'Strong engineering and computing research output.',
    page: 'tamu.html'
  },
  utdallas: {
    name: 'University of Texas at Dallas',
    location: 'Richardson/Dallas, Texas, USA',
    enrollment: '~30,000',
    in: '$13,000',
    out: '$36,000',
    acceptance: 'Moderately selective',
    acceptanceRate: 0.5,
    avgSalary: '$95,000',
    notablePrograms: ['Software Engineering', 'AI', 'Computer Engineering'],
    strengths: 'Regionally respected programs with strong local industry recruitment.',
    costOfLivingIndex: 80,
    pros: 'Strong in AI and growing CS strengths; good regional industry ties.',
    page: 'utdallas.html'
  },
  uh: {
    name: 'University of Houston',
    location: 'Houston, Texas, USA',
    enrollment: '~46,000',
    in: '$8,000',
    out: '$22,000',
    acceptance: 'Accessible',
    acceptanceRate: 0.7,
    avgSalary: '$78,000',
    notablePrograms: ['Software Engineering', 'Data Science', 'Energy Informatics'],
    strengths: 'Affordable education with strong applied programs and local job market access.',
    costOfLivingIndex: 82,
    pros: 'Affordable, diverse, practical software engineering focus.',
    page: 'uh.html'
  },
  ttu: {
    name: 'Texas Tech University',
    location: 'Lubbock, Texas, USA',
    enrollment: '~40,000',
    in: '$9,000',
    out: '$23,000',
    acceptance: 'Moderately selective',
    acceptanceRate: 0.6,
    avgSalary: '$72,000',
    notablePrograms: ['Software Engineering', 'Computer Science'],
    strengths: 'Practical, project-oriented learning with accredited programs.',
    costOfLivingIndex: 70,
    pros: 'ABET-accredited programs with project-based learning.',
    page: 'ttu.html'
  },
  rice: {
    name: 'Rice University',
    location: 'Houston, Texas, USA',
    enrollment: '~8,000',
    in: '$55,000',
    out: '$55,000',
    acceptance: 'Highly selective',
    acceptanceRate: 0.1,
    avgSalary: '$120,000',
    notablePrograms: ['Computer Science', 'Engineering', 'Materials Science'],
    strengths: 'Small student-to-faculty ratio, strong research, excellent career outcomes.',
    costOfLivingIndex: 82,
    pros: 'Private, small classes, strong research and faculty access.',
    page: 'rice.html'
  },
  stanford: {
    name: 'Stanford University',
    location: 'Stanford, California, USA',
    enrollment: '~17,000',
    in: '$60,000',
    out: '$60,000',
    acceptance: 'Extremely selective',
    acceptanceRate: 0.045,
    avgSalary: '$150,000',
    notablePrograms: ['Computer Science', 'AI', 'Entrepreneurship'],
    strengths: 'Elite research, unmatched industry access, and startup ecosystem.',
    costOfLivingIndex: 120,
    pros: 'Top-tier CS and AI; unparalleled Silicon Valley connections.',
    page: 'stanford.html'
  },
  berkeley: {
    name: 'UC Berkeley',
    location: 'Berkeley, California, USA',
    enrollment: '~45,000',
    in: '$14,000',
    out: '$44,000',
    acceptance: 'Highly selective for CS',
    acceptanceRate: 0.12,
    avgSalary: '$140,000',
    notablePrograms: ['Computer Science', 'EECS', 'Data Science'],
    strengths: 'Pioneering research and strong pathways into AI and systems.',
    costOfLivingIndex: 125,
    pros: 'Exceptional theory, systems, and AI research.',
    page: 'berkeley.html'
  },
  caltech: {
    name: 'Caltech',
    location: 'Pasadena, California, USA',
    enrollment: '~2,200',
    in: '$60,000',
    out: '$60,000',
    acceptance: 'Extremely selective',
    acceptanceRate: 0.07,
    avgSalary: '$145,000',
    notablePrograms: ['Computer Science', 'Physics', 'Engineering'],
    strengths: 'Very small student body with deep research opportunities and mentorship.',
    costOfLivingIndex: 118,
    pros: 'Small, intense research-focused environment.',
    page: 'caltech.html'
  },
  ucla: {
    name: 'UCLA',
    location: 'Los Angeles, California, USA',
    enrollment: '~45,000',
    in: '$13,000',
    out: '$43,000',
    acceptance: 'Selective',
    acceptanceRate: 0.18,
    avgSalary: '$115,000',
    notablePrograms: ['Computer Science', 'Visual Computing', 'AI'],
    strengths: 'Broad strengths across CS subfields and strong placement in LA tech.',
    costOfLivingIndex: 115,
    pros: 'Strong across many CS subfields with excellent placement.',
    page: 'ucla.html'
  },
  usc: {
    name: 'USC',
    location: 'Los Angeles, California, USA',
    enrollment: '~48,000',
    in: '$60,000',
    out: '$60,000',
    acceptance: 'Selective',
    acceptanceRate: 0.16,
    avgSalary: '$120,000',
    notablePrograms: ['Computer Science', 'Interactive Media', 'Graphics'],
    strengths: 'Industry-connected programs with strong media and graphics presence.',
    costOfLivingIndex: 115,
    pros: 'Strong industry ties, media and graphics strengths.',
    page: 'usc.html'
  },
  ucsd: {
    name: 'UC San Diego',
    location: 'La Jolla, California, USA',
    enrollment: '~40,000',
    in: '$14,000',
    out: '$44,000',
    acceptance: 'Selective',
    acceptanceRate: 0.2,
    avgSalary: '$110,000',
    notablePrograms: ['Computer Science', 'Bioinformatics', 'Systems'],
    strengths: 'Strong systems research and interdisciplinary computational biology ties.',
    costOfLivingIndex: 120,
    pros: 'Very strong in systems and computational biology intersections.',
    page: 'ucsd.html'
  },
  uci: {
    name: 'UC Irvine',
    location: 'Irvine, California, USA',
    enrollment: '~36,000',
    in: '$13,000',
    out: '$43,000',
    acceptance: 'Selective',
    acceptanceRate: 0.25,
    avgSalary: '$100,000',
    notablePrograms: ['Computer Science', 'Software Engineering', 'Data Science'],
    strengths: 'Balanced cost/quality with solid research and strong industry links in Orange County.',
    costOfLivingIndex: 110,
    pros: 'Good balance of cost and quality; solid research programs.',
    page: 'uci.html'
  },
  sjsu: {
    name: 'San Jose State University',
    location: 'San Jose, California, USA',
    enrollment: '~33,000',
    in: '$8,000',
    out: '$25,000',
    acceptance: 'Accessible',
    acceptanceRate: 0.65,
    avgSalary: '$95,000',
    notablePrograms: ['Software Engineering', 'Internship-focused CS programs'],
    strengths: 'Direct access to Silicon Valley internships and hiring pipelines.',
    costOfLivingIndex: 140,
    pros: 'Affordable Bay Area option with strong Silicon Valley internship access.',
    page: 'sjsu.html'
  },
  csuf: {
    name: 'California State University, Fullerton',
    location: 'Fullerton, California, USA',
    enrollment: '~40,000',
    in: '$8,000',
    out: '$25,000',
    acceptance: 'Accessible',
    acceptanceRate: 0.6,
    avgSalary: '$80,000',
    notablePrograms: ['Software Development', 'Information Systems'],
    strengths: 'Career-focused programs with good regional employer connections.',
    costOfLivingIndex: 95,
    pros: 'Affordable and career-focused with strong software development emphasis.',
    page: 'csuf.html'
  }
};
